name = "tabataroulette"
type = "webpack"

account_id = "2b41aaa8684b2a75f291109adfb626ba"
workers_dev = true
route = "tabataroulette.isnow.online/*"
compatibility_date = "2022-02-08"
main="./workers-site/index.js"

[site]
bucket = "./public"
